name: flutter_ink_web_check_in
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  circle_flags: ^4.0.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.2
  pdfrx: ^0.4.10
  shared_preferences: ^2.2.2
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  very_good_analysis: ^5.1.0
  widget_zoom: ^0.0.3
  flutter_wallet_card:
    git:
      url: https://github.com/Jsmorales1415/flutter_wallet_card.git
      ref: master
  flutter_slidable: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  build_test: ^2.2.2
  fake_async: ^1.3.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  slang_build_runner: ^3.29.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logos/

  fonts:
    - family: ClanOT
      fonts:
        - asset: assets/fonts/ClanOT/ClanOT-Black.otf
        - asset: assets/fonts/ClanOT/ClanOT-Bold.otf
        - asset: assets/fonts/ClanOT/ClanOT-Book.otf
        - asset: assets/fonts/ClanOT/ClanOT-Medium.otf
        - asset: assets/fonts/ClanOT/ClanOT-News.otf
        - asset: assets/fonts/ClanOT/ClanOT-Regular.otf
        - asset: assets/fonts/ClanOT/ClanOT-Thin.otf
        - asset: assets/fonts/ClanOT/ClanOT-Ultra.otf
        - asset: assets/fonts/ClanOT/ChambersSansOT.otf
